apiVersion: apps/v1
kind: Deployment
metadata:
  name: kauewe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kauewe
  template:
    metadata:
      labels:
        app: kauewe
    spec:
      containers:
      - image: okteto.dev/kauewe:latest
        name: kauewe
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "860f35c0-f0dc-4665-8291-84ed457c7bc6"
        - name: Vless_Path
          value: "/vldjj4e94ds"
        - name: Vmess_UUID
          value: "860f35c0-f0dc-4665-8291-84ed457c7bc6"
        - name: Vmess_Path
          value: "/vm67hbh65yh5t"
        - name: Share_Path
          value: "/v2link"
